### ISSUE TITLE
Migrate to @ConfigurationProperties

### ISSUE THREAD

**Issue by snicoll** [Unicon/cas-client-autoconfig-support#1]
Hi,

Instead of `@Value`, could you please migrate these to a simple POJO annotated with `@ConfigurationProperties`. This not only gives you better support for relaxed binding but if you enable the `spring-boot-configuration-processor` you'll offer content assist for those keys in the IDE (STS, Intellij IDEA and Netbeans are offering such Spring Boot support now)

I am happy to help you migrating to that model.

See also [the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata)

**Comment by dima767** [comment]
Absolutely. Help is always welcomed! :-)

**Comment by dima767** [comment]
This is done. `1.0.0-RC1` is released.
