### ISSUE TITLE
spring boot cas

### ISSUE THREAD

**Issue by zhugezifang** [Unicon/cas-client-autoconfig-support#12]
can you give a demo of spring boot use it?

**Comment by spairy** [comment]
1. Generate a springboot application in "https://start.spring.io/" with Selected Dependencies "Web".
2. add dependency  in pom.xml with following:
`<dependency>`
    `    <groupId>net.unicon.cas</groupId>`
    `    <artifactId>cas-client-autoconfig-support</artifactId>`
    `    <version>1.5.0-GA</version>`
`</dependency>`
3. add "@EnableCasClient" in root Application.java file.
4. add properties with following:
`   cas.server-url-prefix=http://xxx.xxx.xxx.xxx:xxxx/cas`
`   cas.server-login-url=http://xxx.xxx.xxx.xxx:xxxx/cas/login`
`   cas.client-host-url=http://localhost:8080`
`   cas.validation-type=CAS`
5. create controller.
6. start application.

**Comment by dima767** [comment]
https://github.com/UniconLabs/bootiful-cas-client
