### ISSUE TITLE
Protecting URLs based on the attributes returned from the principal

### ISSUE THREAD

**Issue by BLTSEC** [Unicon/cas-client-autoconfig-support#13]
I was wondering if there was a way to use the attributes returned from the principal to protect certain URLs globally. Currently I am handling the check in each controller method like this using a custom util class:

`Optional<Map> attributes = userUtil.hasAuthority(request);
        if(!attributes.isPresent()) {
            return "redirect:/401";
        }`

The specific attributes I am checking against is the return of certain Active Directory groups. An example of what I want would be something along the lines of what Spring Security offers: 

`@Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .authorizeRequests()
                .antMatchers("/").hasAuthority("ADGroup");`

I really appreciate all of the work you've done on this project, it has helped us out tremendously and would really appreciate some guidance with this step.

Thank you,
Brennan Turner

**Comment by dima767** [comment]
This type of a request for functionality would be better addressed at Java CAS client project, as this Spring Boot starter is merely utilizing functionality of that library and exposing it to Spring Boot apps. No more, no less.
