### ISSUE TITLE
Consider adding Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [Unicon/cas-client-autoconfig-support#14]
Relates to https://github.com/spring-projects/spring-boot/issues/13510

We are reviewing our [community starters list](https://github.com/spring-projects/spring-boot/blob/7683d346e31bbe0313a03ce487ee59454665a143/spring-boot-project/spring-boot-starters/README.adoc) and a quick look here suggests that this starter doesn’t yet support Spring Boot 2.

Can you please let us know if/when you plan to support Spring Boot 2?

Thanks!

**Comment by dima767** [comment]
Thanks for the suggestion. It’s unknown when Boot 2 support will be added, but it is a good suggestion nevertheless to start looking into

**Comment by dima767** [comment]
This is done now.
