### ISSUE TITLE
From the code, I could not see when and where to register SingleSignOutFilter filter.

### ISSUE THREAD

**Issue by liudonghua123** [Unicon/cas-client-autoconfig-support#15]
How to register [`SingleSignOutFilter`](https://github.com/apereo/java-cas-client/blob/master/cas-client-core/src/main/java/org/jasig/cas/client/session/SingleSignOutFilter.java) filter and how can I process logout request correctly?

**Comment by dima767** [comment]
Not implemented. Contributions are always welcomed.
