### ISSUE TITLE
How do you retrieve the user principal and attributes from the cas client

### ISSUE THREAD

**Issue by dbollaer** [Unicon/cas-client-autoconfig-support#2]
Hello,

I have successfully configured the cas client, but I fail to retrieve the user principal and attributes.
The following code always show "No user"

``` java
    public static String getCurrentLogin() {
        SecurityContext securityContext = SecurityContextHolder.getContext();
        Authentication authentication = securityContext.getAuthentication();
        String userName = "No user";

        if (authentication != null) {
            if (authentication.getPrincipal() instanceof UserDetails) {
                UserDetails springSecurityUser = (UserDetails) authentication.getPrincipal();
                userName = springSecurityUser.getUsername();
            } else if (authentication.getPrincipal() instanceof String) {
                userName = (String) authentication.getPrincipal();
            }
            userName = "No username";
        }

        return userName;
    }
```

Thank you in advance.

**Comment by dima767** [comment]
There is no Spring Security involved here at all. This configuration simply uses straight up CAS Java client library (filters, etc.) and exposes its `AttributePrincipal` as a standard remote user in http servlet request. Here's a sample of the client boot app using this auto config library, and how you get the authenticated principal from http servlet request: https://github.com/UniconLabs/bootiful-cas-client/blob/master/src/main/groovy/net/unicon/cas/client/demo/MainController.groovy#L26

Cheers,
D.
