### ISSUE TITLE
cas logout url?

### ISSUE THREAD

**Issue by jebmiller** [Unicon/cas-client-autoconfig-support#3]
Is there a property for cas.server-logout-url? How does one go about configuring/implementing CAS logout functionality?

**Comment by dima767** [comment]
Haven't looked/implemented the logout functionality yet. Putting it on my todo for early next year (Jan)

**Comment by dima767** [comment]
BTW, pull requests are always welcomed ;-)

**Comment by jebmiller** [comment]
right on! how can I do a local build?

CIO054879MacBookPro:cas-client-autoconfig-support jmiller$ gradle build

FAILURE: Build failed with an exception.
- Where:

Build file
'/Users/jmiller/Documents/projects/github/cas-client-autoconfig-support/build.gradle'
line: 92
- What went wrong:

A problem occurred evaluating root project 'cas-client-autoconfig-support'.

> No such property: bintrayUsername for class:
> org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
- Try:

Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

Total time: 3.765 secs

On Mon, Dec 28, 2015 at 2:34 PM, Dmitriy Kopylenko <notifications@github.com

> wrote:
> 
> BTW, pull requests are always welcomed ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unicon/cas-client-autoconfig-support/issues/3#issuecomment-167635372
> .

## 

Jeb Miller
Programmer Analyst - Sakai, HJF
USUHS/ATD
4301 Jones Bridge Road
Bethesda, MD 20814-4799
301-319-0442

**Comment by scalding** [comment]
Might consider uncommenting the following lines: [https://github.com/Unicon/cas-client-autoconfig-support/blob/master/gradle.properties#L13-L18]. You won't be able to deploy or sign, but the project should not require that for anyone except those wanting to deploy to bintray.

**Comment by jebmiller** [comment]
Thanks for the tip, I also had to comment out the following in build.grade:

//signing {

//    required { gradle.taskGraph.hasTask("uploadArchives") }

//    sign configurations.archives

//}

got a successful build:

CIO054879MacBookPro:cas-client-autoconfig-support jmiller$ gradle build

:processResources UP-TO-DATE

:compileJava UP-TO-DATE

:classes UP-TO-DATE

:jar UP-TO-DATE

:javadoc UP-TO-DATE

:javadocJar UP-TO-DATE

:sourcesJar UP-TO-DATE

:assemble UP-TO-DATE

:compileTestJava UP-TO-DATE

:processTestResources UP-TO-DATE

:testClasses UP-TO-DATE

:test UP-TO-DATE

:check UP-TO-DATE

:build UP-TO-DATE

BUILD SUCCESSFUL

Total time: 4.155 secs

This build could be faster, please consider using the Gradle Daemon:
https://docs.gradle.org/2.7/userguide/gradle_daemon.html

On Mon, Dec 28, 2015 at 4:28 PM, Jj notifications@github.com wrote:

> Might consider uncommenting the following lines: [
> https://github.com/Unicon/cas-client-autoconfig-support/blob/master/gradle.properties#L13-L18].
> You won't be able to deploy or sign, but the project should not require
> that for anyone except those wanting to deploy to bintray.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Unicon/cas-client-autoconfig-support/issues/3#issuecomment-167661459
> .

## 

Jeb Miller
Programmer Analyst - Sakai, HJF
USUHS/ATD
4301 Jones Bridge Road
Bethesda, MD 20814-4799
301-319-0442

**Comment by charybr** [comment]
Hi,

Would like to know, if this is done. Is it part of 1.3.0-GA?
Thanks!

Best Regards,
Chary

**Comment by dima767** [comment]
Nothing to do here. See an example here how logout is implemented on the client side: https://github.com/UniconLabs/bootiful-cas-client/blob/master/src/main/resources/application.yml#L24

**Comment by charybr** [comment]
Thanks! I will refer the example.
