### ISSUE TITLE
how to get login user info

### ISSUE THREAD

**Issue by binlaniua** [Unicon/cas-client-autoconfig-support#4]

**Comment by binlaniua** [comment]
session.getAttribute(AbstractCasFilter.xxx)   use this ?

**Comment by dima767** [comment]
`request.getUserPrincipal()`. See this: https://github.com/UniconLabs/bootiful-cas-client/blob/master/src/main/groovy/net/unicon/cas/client/demo/MainController.groovy#L26

https://github.com/UniconLabs/bootiful-cas-client
