### ISSUE TITLE
Any example?

### ISSUE THREAD

**Issue by metti222** [Unicon/cas-client-autoconfig-support#5]
Hi
I am pretty new to CAS. I have an Spring-boot application which i want to use CAS to authenticate. 
I couldnt find any good and up to date example using CAS on Spring boot. I came across this project and it seems perfect to my use, but i cant use it. I tried to use your guide but it doesnt work. I cant even compile my application anymore. When i remove scope runtime  from the  maven dependency then i get another compilation error 
Error:java: java.lang.NoClassDefFoundError: org/json/JSONException
I dont find where the problem is.

Is there any example using this project?

**Comment by dima767** [comment]
https://github.com/UniconLabs/bootiful-cas-client
